{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "39e68194",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: opencv-python in c:\\users\\pc\\appdata\\roaming\\python\\python39\\site-packages (4.7.0.72)\n",
      "Requirement already satisfied: numpy>=1.19.3 in c:\\programdata\\anaconda3\\lib\\site-packages (from opencv-python) (1.21.5)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install opencv-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "346cb462",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "583368b6",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'dlib'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_12632\\3121961382.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mdlib\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mwinsound\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;31m# Load the pre-trained face recognition model\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'dlib'"
     ]
    }
   ],
   "source": [
    "import dlib\n",
    "import winsound\n",
    "\n",
    "# Load the pre-trained face recognition model\n",
    "face_detector = dlib.get_frontal_face_detector()\n",
    "face_recognizer = dlib.face_recognition_model_v1('path_to_face_model.dat')\n",
    "\n",
    "known_faces = {\n",
    "    'person1': 'path_to_person1_image.jpg',\n",
    "    'person2': 'path_to_person2_image.jpg',\n",
    "    # Add more known faces as needed\n",
    "}\n",
    "\n",
    "# Load the known face images and their encodings\n",
    "known_encodings = {}\n",
    "for name, image_path in known_faces.items():\n",
    "    image = dlib.load_rgb_image(image_path)\n",
    "    face_encoding = face_recognizer.compute_face_descriptor(image)\n",
    "    known_encodings[name] = face_encoding\n",
    "\n",
    "cam = cv2.VideoCapture(0)\n",
    "while cam.isOpened():\n",
    "    ret, frame1 = cam.read()\n",
    "    ret, frame2 = cam.read()\n",
    "    diff = cv2.absdiff(frame1, frame2)\n",
    "    gray = cv2.cvtColor(diff, cv2.COLOR_RGB2GRAY)\n",
    "    blur = cv2.GaussianBlur(gray, (5, 5), 0)\n",
    "    _, thresh = cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)\n",
    "    dilated = cv2.dilate(thresh, None, iterations=3)\n",
    "    contours, _ = cv2.findContours(dilated, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)\n",
    "\n",
    "    for c in contours:\n",
    "        if cv2.contourArea(c) < 5000:\n",
    "            continue\n",
    "        x, y, w, h = cv2.boundingRect(c)\n",
    "\n",
    "        # Extract the face region from the frame\n",
    "        face = frame1[y:y+h, x:x+w]\n",
    "\n",
    "        # Convert the face region to grayscale\n",
    "        face_gray = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)\n",
    "\n",
    "        # Detect faces in the grayscale face region\n",
    "        faces = face_detector(face_gray)\n",
    "\n",
    "        # Iterate over the detected faces\n",
    "        for detected_face in faces:\n",
    "            # Compute the face encoding\n",
    "            face_encoding = face_recognizer.compute_face_descriptor(face_gray, detected_face)\n",
    "\n",
    "            # Compare the face encoding with known encodings\n",
    "            for name, known_encoding in known_encodings.items():\n",
    "                # Calculate the Euclidean distance between the face encodings\n",
    "                distance = dlib.distance(face_encoding, known_encoding)\n",
    "\n",
    "                # Set a threshold for face recognition\n",
    "                if distance < 0.5:\n",
    "                    # Known person detected, skip the alarm\n",
    "                    break\n",
    "            else:\n",
    "                # Unknown person detected, trigger the alarm\n",
    "                cv2.rectangle(frame1, (x, y), (x+w, y+h), (0, 255, 0), 2)\n",
    "                winsound.PlaySound('alert.wav', winsound.SND_ASYNC)\n",
    "\n",
    "    if cv2.waitKey(10) == ord('q'):\n",
    "        break\n",
    "    cv2.imshow('Home Security', frame1)\n",
    "\n",
    "cv2.destroyAllWindows()\n",
    "cam.release()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1e5fb36e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting dlib\n",
      "  Using cached dlib-19.24.2.tar.gz (11.8 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'done'\n",
      "  Preparing metadata (pyproject.toml): started\n",
      "  Preparing metadata (pyproject.toml): finished with status 'done'\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (pyproject.toml): started\n",
      "  Building wheel for dlib (pyproject.toml): finished with status 'error'\n",
      "Failed to build dlib\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  Building wheel for dlib (pyproject.toml) did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [73 lines of output]\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_ext\n",
      "  <string>:125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "  Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-4wekbkpi\\dlib_79670f8c39e04b4da431aef6a901df79\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-4wekbkpi\\dlib_79670f8c39e04b4da431aef6a901df79\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\ProgramData\\Anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-4wekbkpi\\dlib_79670f8c39e04b4da431aef6a901df79\\build\\lib.win-amd64-cpython-39 -A x64'\n",
      "  -- Building for: NMake Makefiles\n",
      "  CMake Error at CMakeLists.txt:5 (message):\n",
      "  \n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "    You must use Visual Studio to build a python extension on windows.  If you\n",
      "    are getting this error it means you have not installed Visual C++.  Note\n",
      "    that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "    development.  You need to install Visual Studio for C++.\n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "  \n",
      "  \n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 363, in <module>\n",
      "      main()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 345, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 261, in build_wheel\n",
      "      return _build_backend().build_wheel(wheel_directory, config_settings,\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 416, in build_wheel\n",
      "      return self._build_with_temp_dir(['bdist_wheel'], '.whl',\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 401, in _build_with_temp_dir\n",
      "      self.run_setup()\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 338, in run_setup\n",
      "      exec(code, locals())\n",
      "    File \"<string>\", line 218, in <module>\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\__init__.py\", line 107, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\n",
      "      return run_commands(dist)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\wheel\\bdist_wheel.py\", line 343, in run\n",
      "      self.run_command(\"build\")\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 131, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\dist.py\", line 1244, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\PC\\AppData\\Local\\Temp\\pip-build-env-urt0knyd\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"<string>\", line 130, in run\n",
      "    File \"<string>\", line 167, in build_extension\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\subprocess.py\", line 373, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\PC\\\\AppData\\\\Local\\\\Temp\\\\pip-install-4wekbkpi\\\\dlib_79670f8c39e04b4da431aef6a901df79\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\PC\\\\AppData\\\\Local\\\\Temp\\\\pip-install-4wekbkpi\\\\dlib_79670f8c39e04b4da431aef6a901df79\\\\build\\\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\\\ProgramData\\\\Anaconda3\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\PC\\\\AppData\\\\Local\\\\Temp\\\\pip-install-4wekbkpi\\\\dlib_79670f8c39e04b4da431aef6a901df79\\\\build\\\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects\n"
     ]
    }
   ],
   "source": [
    "pip install dlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b4e81c3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
